[package]
name = "floating-ui-leptos"
description = "Floating UI for Leptos."
homepage = "https://floating-ui.rustforweb.org/frameworks/leptos.html"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
dyn_derive = "0.3.4"
dyn_std = "0.3.3"
floating-ui-dom = { path = "../dom", version = "0.1.3" }
leptos.workspace = true
paste = "1.0.0"
web-sys.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true
